# Generated by Django 4.2.7 on 2023-11-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grading_Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(max_length=255)),
                ('Choice_Field', models.CharField(max_length=255)),
                ('Votes', models.IntegerField()),
            ],
        ),
    ]
